# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_protocol.proto
# Protobuf Python Version: 4.25.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63hat_protocol.proto\x12\x06mubert\"\x83\x01\n\x16M_C_S_INIT_COMPLETIONS\x12<\n\x07proxies\x18\x01 \x01(\x0b\x32+.mubert.M_C_S_INIT_COMPLETIONS.PROXIES_INFO\x1a+\n\x0cPROXIES_INFO\x12\x0c\n\x04http\x18\x01 \x01(\t\x12\r\n\x05https\x18\x02 \x01(\t\"(\n\x16M_S_C_INIT_COMPLETIONS\x12\x0e\n\x06result\x18\x01 \x01(\x08\"-\n\x0cMESSAGE_INFO\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"n\n\x1cM_C_S_CREATE_CHAT_COMPLETION\x12\x0e\n\x06stream\x18\x01 \x01(\x08\x12&\n\x08messages\x18\x02 \x03(\x0b\x32\x14.mubert.MESSAGE_INFO\x12\x16\n\x0emessages_level\x18\x03 \x01(\x05\"\x94\x03\n\x1cM_S_C_CREATE_CHAT_COMPLETION\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x05\x12\r\n\x05model\x18\x04 \x01(\t\x12\x41\n\x07\x63hoices\x18\x05 \x03(\x0b\x32\x30.mubert.M_S_C_CREATE_CHAT_COMPLETION.CHOICE_INFO\x12>\n\x05usage\x18\x06 \x01(\x0b\x32/.mubert.M_S_C_CREATE_CHAT_COMPLETION.USAGE_INFO\x1a_\n\x0b\x43HOICE_INFO\x12\r\n\x05index\x18\x01 \x01(\x05\x12*\n\x0cmessage_body\x18\x02 \x01(\x0b\x32\x14.mubert.MESSAGE_INFO\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\x1aT\n\nUSAGE_INFO\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05*9\n\x0f\x43\x32SMAINPROTOCOL\x12\x18\n\x14\x43\x32SMAINPROTOCOL_NONE\x10\x00\x12\x0c\n\x08\x43_S_CHAT\x10\x01*9\n\x0fS2CMAINPROTOCOL\x12\x18\n\x14S2CMAINPROTOCOL_NONE\x10\x00\x12\x0c\n\x08S_C_CHAT\x10\x01*_\n\x0b\x43\x32SPROTOCOL\x12\x14\n\x10\x43\x32SPROTOCOL_NONE\x10\x00\x12\x19\n\x14\x43_S_INIT_COMPLETIONS\x10\xe9\x07\x12\x1f\n\x1a\x43_S_CREATE_CHAT_COMPLETION\x10\xea\x07*_\n\x0bS2CPROTOCOL\x12\x14\n\x10S2CPROTOCOL_NONE\x10\x00\x12\x19\n\x14S_C_INIT_COMPLETIONS\x10\xd1\x0f\x12\x1f\n\x1aS_C_CREATE_CHAT_COMPLETION\x10\xd2\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SMAINPROTOCOL']._serialized_start=773
  _globals['_C2SMAINPROTOCOL']._serialized_end=830
  _globals['_S2CMAINPROTOCOL']._serialized_start=832
  _globals['_S2CMAINPROTOCOL']._serialized_end=889
  _globals['_C2SPROTOCOL']._serialized_start=891
  _globals['_C2SPROTOCOL']._serialized_end=986
  _globals['_S2CPROTOCOL']._serialized_start=988
  _globals['_S2CPROTOCOL']._serialized_end=1083
  _globals['_M_C_S_INIT_COMPLETIONS']._serialized_start=32
  _globals['_M_C_S_INIT_COMPLETIONS']._serialized_end=163
  _globals['_M_C_S_INIT_COMPLETIONS_PROXIES_INFO']._serialized_start=120
  _globals['_M_C_S_INIT_COMPLETIONS_PROXIES_INFO']._serialized_end=163
  _globals['_M_S_C_INIT_COMPLETIONS']._serialized_start=165
  _globals['_M_S_C_INIT_COMPLETIONS']._serialized_end=205
  _globals['_MESSAGE_INFO']._serialized_start=207
  _globals['_MESSAGE_INFO']._serialized_end=252
  _globals['_M_C_S_CREATE_CHAT_COMPLETION']._serialized_start=254
  _globals['_M_C_S_CREATE_CHAT_COMPLETION']._serialized_end=364
  _globals['_M_S_C_CREATE_CHAT_COMPLETION']._serialized_start=367
  _globals['_M_S_C_CREATE_CHAT_COMPLETION']._serialized_end=771
  _globals['_M_S_C_CREATE_CHAT_COMPLETION_CHOICE_INFO']._serialized_start=590
  _globals['_M_S_C_CREATE_CHAT_COMPLETION_CHOICE_INFO']._serialized_end=685
  _globals['_M_S_C_CREATE_CHAT_COMPLETION_USAGE_INFO']._serialized_start=687
  _globals['_M_S_C_CREATE_CHAT_COMPLETION_USAGE_INFO']._serialized_end=771
# @@protoc_insertion_point(module_scope)
