# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musicdl_protocol.proto
# Protobuf Python Version: 4.25.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16musicdl_protocol.proto\x12\x07musicdl\"r\n\x12M_C_S_SEARCH_MUSIC\x12\x10\n\x08songName\x18\x01 \x01(\t\x12\x0e\n\x06singer\x18\x02 \x01(\t\x12\x13\n\x0bproxiesHttp\x18\x03 \x01(\t\x12\x14\n\x0cproxiesHttps\x18\x04 \x01(\t\x12\x0f\n\x07saveDir\x18\x05 \x01(\t\"\x89\x01\n\x14M_C_S_DOWNLOAD_MUSIC\x12\x10\n\x08songName\x18\x01 \x01(\t\x12\x0e\n\x06singer\x18\x02 \x01(\t\x12\x13\n\x0b\x64ownloadUrl\x18\x03 \x01(\t\x12\x13\n\x0bproxiesHttp\x18\x04 \x01(\t\x12\x14\n\x0cproxiesHttps\x18\x05 \x01(\t\x12\x0f\n\x07saveDir\x18\x06 \x01(\t\"\xb7\x01\n\x12M_S_C_SEARCH_MUSIC\x12:\n\nmusicInfos\x18\x01 \x03(\x0b\x32&.musicdl.M_S_C_SEARCH_MUSIC.MUSIC_INFO\x1a\x65\n\nMUSIC_INFO\x12\x10\n\x08songName\x18\x01 \x01(\t\x12\x0e\n\x06singer\x18\x02 \x01(\t\x12\x13\n\x0b\x64ownloadUrl\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\t\"\x80\x01\n\x14M_S_C_DOWNLOAD_MUSIC\x12\x0f\n\x07\x61udio64\x18\x01 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\x12\x11\n\tsourceUrl\x18\x03 \x01(\t\x12\x10\n\x08songName\x18\x04 \x01(\t\x12\x0e\n\x06singer\x18\x05 \x01(\t\x12\x10\n\x08\x64uration\x18\x06 \x01(\t*<\n\x0f\x43\x32SMAINPROTOCOL\x12\x18\n\x14\x43\x32SMAINPROTOCOL_NONE\x10\x00\x12\x0f\n\x0b\x43_S_MUSICDL\x10\x01*<\n\x0fS2CMAINPROTOCOL\x12\x18\n\x14S2CMAINPROTOCOL_NONE\x10\x00\x12\x0f\n\x0bS_C_MUSICDL\x10\x01*S\n\x0b\x43\x32SPROTOCOL\x12\x14\n\x10\x43\x32SPROTOCOL_NONE\x10\x00\x12\x15\n\x10\x43_S_SEARCH_MUSIC\x10\xe9\x07\x12\x17\n\x12\x43_S_DOWNLOAD_MUSIC\x10\xea\x07*S\n\x0bS2CPROTOCOL\x12\x14\n\x10S2CPROTOCOL_NONE\x10\x00\x12\x15\n\x10S_C_SEARCH_MUSIC\x10\xd1\x0f\x12\x17\n\x12S_C_DOWNLOAD_MUSIC\x10\xd2\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'musicdl_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SMAINPROTOCOL']._serialized_start=608
  _globals['_C2SMAINPROTOCOL']._serialized_end=668
  _globals['_S2CMAINPROTOCOL']._serialized_start=670
  _globals['_S2CMAINPROTOCOL']._serialized_end=730
  _globals['_C2SPROTOCOL']._serialized_start=732
  _globals['_C2SPROTOCOL']._serialized_end=815
  _globals['_S2CPROTOCOL']._serialized_start=817
  _globals['_S2CPROTOCOL']._serialized_end=900
  _globals['_M_C_S_SEARCH_MUSIC']._serialized_start=35
  _globals['_M_C_S_SEARCH_MUSIC']._serialized_end=149
  _globals['_M_C_S_DOWNLOAD_MUSIC']._serialized_start=152
  _globals['_M_C_S_DOWNLOAD_MUSIC']._serialized_end=289
  _globals['_M_S_C_SEARCH_MUSIC']._serialized_start=292
  _globals['_M_S_C_SEARCH_MUSIC']._serialized_end=475
  _globals['_M_S_C_SEARCH_MUSIC_MUSIC_INFO']._serialized_start=374
  _globals['_M_S_C_SEARCH_MUSIC_MUSIC_INFO']._serialized_end=475
  _globals['_M_S_C_DOWNLOAD_MUSIC']._serialized_start=478
  _globals['_M_S_C_DOWNLOAD_MUSIC']._serialized_end=606
# @@protoc_insertion_point(module_scope)
