# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main_protocol.proto
# Protobuf Python Version: 4.25.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13main_protocol.proto\x12\rmain_protocol\"e\n\x03\x43\x32S\x12\x0e\n\x06syncId\x18\x01 \x01(\x03\x12\x15\n\rserver_syncId\x18\x02 \x01(\x03\x12\x10\n\x08protocol\x18\x03 \x01(\x05\x12\x14\n\x0csub_protocol\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\"e\n\x03S2C\x12\x0e\n\x06syncId\x18\x01 \x01(\x03\x12\x15\n\rserver_syncId\x18\x02 \x01(\x03\x12\x10\n\x08protocol\x18\x03 \x01(\x05\x12\x14\n\x0csub_protocol\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c*5\n\x0b\x43\x32SPROTOCOL\x12\x14\n\x10\x43\x32SPROTOCOL_NONE\x10\x00\x12\x10\n\nC_S_CHROMA\x10\xb5\xd3=*5\n\x0bS2CPROTOCOL\x12\x14\n\x10S2CPROTOCOL_NONE\x10\x00\x12\x10\n\nS_C_CHROMA\x10\xf5\xd7zb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SPROTOCOL']._serialized_start=244
  _globals['_C2SPROTOCOL']._serialized_end=297
  _globals['_S2CPROTOCOL']._serialized_start=299
  _globals['_S2CPROTOCOL']._serialized_end=352
  _globals['_C2S']._serialized_start=38
  _globals['_C2S']._serialized_end=139
  _globals['_S2C']._serialized_start=141
  _globals['_S2C']._serialized_end=242
# @@protoc_insertion_point(module_scope)
