# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mubert_protocol.proto
# Protobuf Python Version: 4.25.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mubert_protocol.proto\x12\x06mubert\"p\n\x12M_C_S_CREATE_MUSIC\x12\x0c\n\x04tags\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x03\x12\x13\n\x0bproxiesHttp\x18\x03 \x01(\t\x12\x14\n\x0cproxiesHttps\x18\x04 \x01(\t\x12\x0f\n\x07saveDir\x18\x05 \x01(\t\"J\n\x12M_S_C_CREATE_MUSIC\x12\x0f\n\x07\x61udio64\x18\x01 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\x12\x11\n\tsourceUrl\x18\x03 \x01(\t*;\n\x0f\x43\x32SMAINPROTOCOL\x12\x18\n\x14\x43\x32SMAINPROTOCOL_NONE\x10\x00\x12\x0e\n\nC_S_MUBERT\x10\x01*;\n\x0fS2CMAINPROTOCOL\x12\x18\n\x14S2CMAINPROTOCOL_NONE\x10\x00\x12\x0e\n\nS_C_MUBERT\x10\x01*:\n\x0b\x43\x32SPROTOCOL\x12\x14\n\x10\x43\x32SPROTOCOL_NONE\x10\x00\x12\x15\n\x10\x43_S_CREATE_MUSIC\x10\xe9\x07*:\n\x0bS2CPROTOCOL\x12\x14\n\x10S2CPROTOCOL_NONE\x10\x00\x12\x15\n\x10S_C_CREATE_MUSIC\x10\xd1\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mubert_protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_C2SMAINPROTOCOL']._serialized_start=223
  _globals['_C2SMAINPROTOCOL']._serialized_end=282
  _globals['_S2CMAINPROTOCOL']._serialized_start=284
  _globals['_S2CMAINPROTOCOL']._serialized_end=343
  _globals['_C2SPROTOCOL']._serialized_start=345
  _globals['_C2SPROTOCOL']._serialized_end=403
  _globals['_S2CPROTOCOL']._serialized_start=405
  _globals['_S2CPROTOCOL']._serialized_end=463
  _globals['_M_C_S_CREATE_MUSIC']._serialized_start=33
  _globals['_M_C_S_CREATE_MUSIC']._serialized_end=145
  _globals['_M_S_C_CREATE_MUSIC']._serialized_start=147
  _globals['_M_S_C_CREATE_MUSIC']._serialized_end=221
# @@protoc_insertion_point(module_scope)
